/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author fatih
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private AntrianService antrianService;
    /**
     * Creates new form MainFrame
     */
 public MainFrame() {
    initComponents();           // WAJIB, JANGAN DIHAPUS
    antrianService = new AntrianService();

    jLabelAmbilAntrian.setText("000");
    jLabelNomorSekarang.setText("000");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        button1 = new java.awt.Button();
        jLabelJudul = new javax.swing.JLabel();
        jLabelAntrianSekarang = new javax.swing.JLabel();
        jButtonAmbilAntrian = new javax.swing.JButton();
        jButtonPanggilAntrian = new javax.swing.JButton();
        jLabelNomorSekarang = new javax.swing.JLabel();
        jLabelAmbilAntrian = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlDkShadow);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelJudul.setFont(new java.awt.Font("Selawik Light", 1, 18)); // NOI18N
        jLabelJudul.setText("SISTEM ANTRIAN LOKET PELAYANAN");
        jLabelJudul.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelAntrianSekarang.setBackground(java.awt.SystemColor.activeCaption);
        jLabelAntrianSekarang.setFont(new java.awt.Font("Inter Black", 2, 13)); // NOI18N
        jLabelAntrianSekarang.setText("Antrian sekarang");
        jLabelAntrianSekarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAmbilAntrian.setBackground(java.awt.SystemColor.control);
        jButtonAmbilAntrian.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jButtonAmbilAntrian.setText("Ambil Antrian");
        jButtonAmbilAntrian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAmbilAntrian.addActionListener(this::jButtonAmbilAntrianActionPerformed);

        jButtonPanggilAntrian.setBackground(java.awt.SystemColor.control);
        jButtonPanggilAntrian.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jButtonPanggilAntrian.setText("Panggil Antrian");
        jButtonPanggilAntrian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPanggilAntrian.addActionListener(this::jButtonPanggilAntrianActionPerformed);

        jLabelNomorSekarang.setBackground(new java.awt.Color(153, 255, 102));
        jLabelNomorSekarang.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabelNomorSekarang.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNomorSekarang.setText("000");
        jLabelNomorSekarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelAmbilAntrian.setBackground(new java.awt.Color(153, 255, 153));
        jLabelAmbilAntrian.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jLabelAmbilAntrian.setForeground(new java.awt.Color(51, 51, 255));
        jLabelAmbilAntrian.setLabelFor(jButtonAmbilAntrian);
        jLabelAmbilAntrian.setText("000");
        jLabelAmbilAntrian.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButtonReset.setText("Reset");
        jButtonReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelJudul)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReset)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAmbilAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAmbilAntrian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabelNomorSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabelAntrianSekarang))))
                    .addComponent(jButtonPanggilAntrian))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAmbilAntrian)
                    .addComponent(jLabelAntrianSekarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAmbilAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomorSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPanggilAntrian)
                .addGap(30, 30, 30)
                .addComponent(jButtonReset)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilAntrianActionPerformed
    int nomor = antrianService.ambilAntrian();
    jLabelAmbilAntrian.setText(String.format("%03d", nomor));        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAmbilAntrianActionPerformed

    private void jButtonPanggilAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanggilAntrianActionPerformed
     int nomor = antrianService.panggilAntrian();
    jLabelNomorSekarang.setText(String.format("%03d", nomor));    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPanggilAntrianActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
 antrianService.reset();

    jLabelAmbilAntrian.setText("000");
    jLabelNomorSekarang.setText("000");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButtonAmbilAntrian;
    private javax.swing.JButton jButtonPanggilAntrian;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabelAmbilAntrian;
    private javax.swing.JLabel jLabelAntrianSekarang;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelNomorSekarang;
    // End of variables declaration//GEN-END:variables
}
